# name: CI Workflow

# on:
#     push:
#         branches:
#             - main

# jobs:
#     build:
#         runs-on: [self-hosted]
#         steps:
#             - name: Checkout code
#               uses: actions/checkout@v2

#             - name: Install dependencies
#               run: pnpm install

#             - name: Build project
#               run: pnpm run build:prod

#             - name: Build Docs
#               run: pnpm run docs:build

#             - name: Deploy to nginx
#               run: |
#                 sudo cp -r dist/* /usr/share/nginx/html

#             - name: Verify deployment
#               run: |
#                 echo "Deployment completed successfully " 
#                 ls -la /usr/share/nginx/html
